on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: rkhazh/first_dock
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - run: make test
    - run: make integration_test
    - name: Build
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build

  coverage:
    runs-on: ubuntu-latest
    container: rkhazh/first_dock
    needs: [build_and_test]
    steps:
    - uses: actions/checkout@v2 
    - run: mkdir build
    - uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build
    - run: make lcov
